# Configuration file for car bluetooth reader

logging: 'DEBUG'     # CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET

serial:
   # Bluetooth and rfcomm
   port: '/dev/ttyS0'
   port_simulate: '/dev/pts/1'  
   baudrate: 115200
   parity: PARITY_NONE
   stopbits: STOPBITS_ONE
   bytesize: EIGHTBITS
   timeout: 1
   ports_list:
      - '/dev/ttyS[0-9]'
      - '/dev/ttyUSB[0-9]'

sensors:
   port: "yes"

simcom:
   bps: 115200
   powerkey: 4
   serial_dev: '/dev/ttyS0'
   sim:
      pina: "3522"
      apn: "m2m.movistar.es"
      CMNB: 2
      CNMP: 2
      CBANDCFG: 
         - catm = "1,2,3,4,5,8,12,13,14,18,19,20,25,26,27,28,66,85"
         - nb = "20"
      nbchannels: '20,21'
      catmchannels: '19,20'

   mqtt:
      host: 'broker.emqx.io'
      port: 1883
      qos: 2
      keepalive: 60
      topic: "root/IECI/client/<device_id>/"
      topic_pub: "root/IECI/client/<device_id>/"
      topic_sub: 
         - command
         - other

    
    
    
    
    
    
    
    
